# Generated by Django 5.2.7 on 2026-03-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_teamassignment_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='projects.teammember'),
        ),
        migrations.AlterUniqueTogether(
            name='teamassignment',
            unique_together={('team_member', 'task')},
        ),
    ]
